[meta]
name = "UiNav"
author = "ar....."
version = "0.1.0"
category = "Libraries"

[script]
module = "UiNav"
exports = [
  "src/Exports/api.as"
]
shared_exports = [
  "src/core/types.as"
]
optional_dependencies = []
