namespace UiNav {
namespace LayerTags {

    const string CFG = "UiLayers.cfg";
    bool g_Loaded = false;
    dictionary g_Tags;
    string g_LastPath = "";

    void EnsureLoaded() {
        if (!g_Loaded) {
            g_Loaded = true;
            _Load();
        }
    }

    void Reload() {
        g_Loaded = true;
        _Load();
    }

    string _CfgPath() {
        return IO::FromStorageFolder(CFG);
    }

    void _Load() {
        g_Tags.DeleteAll();
        string path = _CfgPath();
        g_LastPath = path;
        if (!IO::FileExists(path)) return;

        IO::File f(path, IO::FileMode::Read);
        array<string>@ lines = f.ReadToEnd().Split("\n");
        f.Close();

        for (uint i = 0; i < lines.Length; ++i) {
            string ln = lines[i].Trim();
            if (ln.Length == 0 || ln.StartsWith("#")) continue;

            int eq = ln.IndexOf("=");
            if (eq < 0) continue;
            string lhs = ln.SubStr(0, eq).Trim();
            string rhs = ln.SubStr(eq + 1).Trim();
            if (lhs.Length == 0) continue;

            rhs = _SanitizeTag(rhs);
            if (rhs.Length == 0) continue;

            g_Tags[lhs] = rhs;
        }
    }

    void Save() {
        EnsureLoaded();
        string path = _CfgPath();
        g_LastPath = path;

        string outText = "# UiLayers.cfg - generated by UiNav LayerTags\n";

        array<string> keys = g_Tags.GetKeys();
        keys.SortAsc();
        for (uint i = 0; i < keys.Length; ++i) {
            string key = keys[i];
            string val;
            if (!g_Tags.Get(key, val)) continue;
            if (val.Length == 0) continue;
            outText += key + " = " + val + "\n";
        }
        _IO::File::WriteFile(path, outText, false);
    }

    string GetTag(const string &in key) {
        EnsureLoaded();
        string v;
        if (g_Tags.Get(key, v)) return v;
        return "";
    }

    void SetTag(const string &in key, const string &in tag) {
        EnsureLoaded();
        string k = _SanitizeKey(key);
        if (k.Length == 0) return;
        string v = _SanitizeTag(tag);
        if (v.Length == 0) {
            g_Tags.Delete(k);
        } else {
            g_Tags[k] = v;
        }
        Save();
    }

    string KeyForLayer(CGameUILayer@ layer, int layerIx = -1) {
        if (layer is null) return "";

        string key = "ml:";
        if (layerIx >= 0) key += "ix=" + layerIx + "|";

        if (layer.LocalPage !is null && layer.LocalPage.MainFrame !is null) {
            string id = layer.LocalPage.MainFrame.ControlId;
            if (id.Length > 0) key += "id=" + _SanitizeKey(id) + "|";
        }

        if (layer.AttachId.Length > 0) {
            key += "attach=" + _SanitizeKey(layer.AttachId) + "|";
        }

        string name = _ExtractMlName(layer.ManialinkPageUtf8);
        if (name.Length == 0) name = _ExtractMlName("" + layer.ManialinkPage);
        if (name.Length > 0) key += "name=" + _SanitizeKey(name) + "|";

        string page = layer.ManialinkPageUtf8;
        if (page.Length == 0) page = "" + layer.ManialinkPage;
        if (page.Length > 0) key += "hash=" + _FastPageHash(page) + "|";

        if (key.EndsWith("|")) key = key.SubStr(0, key.Length - 1);
        if (key == "ml:") return "";
        return key;
    }

    string GetTagForLayer(CGameUILayer@ layer, int layerIx = -1) {
        string key = KeyForLayer(layer, layerIx);
        if (key.Length == 0) return "";
        return GetTag(key);
    }

    void SetTagForLayer(CGameUILayer@ layer, const string &in tag, int layerIx = -1) {
        string key = KeyForLayer(layer, layerIx);
        if (key.Length == 0) return;
        SetTag(key, tag);
    }

    string GetLastPath() {
        EnsureLoaded();
        return g_LastPath;
    }

    string _ExtractMlName(const string &in page) {
        if (page.Length == 0) return "";
        int idx = _IndexOfFrom(page, "name=\"", 0);
        if (idx < 0) return "";
        idx += 6;
        int end = _IndexOfFrom(page, "\"", idx);
        if (end < 0 || end <= idx) return "";
        return page.SubStr(idx, end - idx);
    }

    string _FastPageHash(const string &in page) {
        int len = int(page.Length);
        if (len <= 0) return "";
        if (len <= 8192) return Crypto::MD5(page);
        int headLen = Math::Min(len, 512);
        int tailLen = Math::Min(len, 512);
        string head = page.SubStr(0, headLen);
        string tail = (len > tailLen) ? page.SubStr(len - tailLen, tailLen) : page;
        return Crypto::MD5(tostring(len) + "|" + head + "|" + tail);
    }

    int _IndexOfFrom(const string &in hay, const string &in needle, int start) {
        if (start < 0) start = 0;
        int hlen = int(hay.Length);
        int nlen = int(needle.Length);
        if (nlen == 0) return (start <= hlen ? start : -1);
        if (start > hlen - nlen) return -1;
        for (int i = start; i <= hlen - nlen; ++i) {
            if (hay.SubStr(i, nlen) == needle) return i;
        }
        return -1;
    }

    string _SanitizeKey(const string &in raw) {
        string s = raw.Trim();
        if (s.Length == 0) return "";
        s = s.Replace("\r", "").Replace("\n", "");
        s = s.Replace("=", "%3D");
        s = s.Replace("|", "%7C");
        return s;
    }

    string _SanitizeTag(const string &in raw) {
        string s = raw.Trim();
        if (s.Length == 0) return "";
        s = s.Replace("\r", "").Replace("\n", "");
        return s;
    }
}
}
